### ISSUE TITLE
[Newcomer] Seash Scripts

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seash#50]
It would be useful to have the ability to run pre-existing seash scripts.  For example, we could write something like this...

login.seash
```
loadkeys leonwlaw
as leonwlaw
browse
on browsegood
```

and then from within seash...

```
 !> script login.seash
 leonwlaw@browsegood !>
```

Or if we want to do some debugging...
```
 !> script login.seash verbose
 !> loadkeys leonwlaw
 !> as leonwlaw
 leonwlaw@ !> browse
 leonwlaw@ !> on browsegood
 leonwlaw@browsegood !>
```

In addition, maybe the module can also run a script specified directly from the command line. 

```sh
leonwlaw > python seash.py --script login.seash [--verbose]
-- Factoid text --
Enabled modules: ....
 leonwlaw@browsegood !>
```

**Comment by aaaaalbert** [comment]
I'll give this a WONTFIX. A new seash-like experiment tool could make better use of an interactive Python prompt (see the [`interactive_repy_console`](https://github.com/aaaaalbert/repy-doodles/blob/master/interactive_repy_console.py#L16-L17) doodle for a possible way to do this).

Also, you can always use the experiment library interactively.
