### ISSUE TITLE
[Newcomer] View Resources filtering

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seash#52]
The current ```view resources``` command prints out the entire contents of the resources files on each vessel. This can be annoying when trying to find a particular resource line, i.e. allowed disk usage, for each vessel.  Perhaps we could create a module to provide users with a better interface to viewing the resource values, i.e. printing out the values in a simple table format, similar to 'list'.

**Comment by aaaaalbert** [comment]
IMHO this is better dealt with using available (but separate) tools like `grep`. Closing.
