### ISSUE TITLE
Command to automatically upload dependencies for RepyV2 scripts

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seash#58]
It would be convenient for the user if we had a command like run that would also upload any module dependencies a repy program had.  For example, if a program dylinks against advertise.repy, it would upload advertise.repy, centralizedadvertise.repy, centralizedadvertise_v2, etc. automatically.

**Comment by aaaaalbert** [comment]
The solution provided in the proposed patch has a few holes I believe (as the regexp won't catch all types of dy_import, etc.)

Here's a less intrusive workaround: Use [`dy_trace_imports`](https://github.com/aaaaalbert/repy-doodles/blob/master/dy_trace_imports.r2py) to find out what libraries your code imports, and the [new `uploaddir` module](https://github.com/SeattleTestbed/seash/tree/master/modules/uploaddir) to push all of the files with a single command.
